// ============================================================
// このファイルはほぼ Next.js の定型コード（npx create-next-app 実行時の初期ファイル）
// なぜ layout.tsx に <Providers> を置くか
//   → Next.js の layout.tsx はアプリ全体を囲む最上位コンポーネント。
//     TanStack Query の QueryClientProvider はアプリ全体でキャッシュを共有するために
//     最上位に置く必要があるため、layout.tsx の <body> の中に入れている。
//     ここに置かないと、ページごとにキャッシュが分断されてデータが共有されない。
// ============================================================
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
